/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni_TestJni */

#ifndef _Included_com_example_testjni_TestJni
#define _Included_com_example_testjni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_TestJni
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_testjni_TestJni_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testjni_TestJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testjni_TestJni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_testjni_TestJni
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testjni_TestJni_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
